; FONDO.ASM
;
; Map Source File.
;
; Info:
;   Section       : ROM0
;   Bank          : 0
;   Map size      : 10 x 10
;   Tile set      : Z:\home\cpc\Escritorio\unbricked\unbricked\src\tilefondo.gbr
;   Plane count   : 0.5 plane (4 bits)
;   Plane order   : Tiles are continues
;   Tile offset   : 0
;   Split data    : No
;
; This file was generated by GBMB v1.8

DEF fondoWidth  EQU 10
DEF fondoHeight EQU 10
DEF fondoBank   EQU 0

 SECTION "ROM0", ROM0

fondo::
DB $00,$00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00

; End of FONDO.Z80
