; MAPAFONDO.Z80
;
; Map Source File.
;
; Info:
;   Section       : Fondo
;   Bank          : 0
;   Map size      : 20 x 18
;   Tile set      : Z:\home\cpc\Escritorio\unbricked\unbricked\src\tilesfondo.gbr
;   Plane count   : 0.5 plane (4 bits)
;   Plane order   : Tiles are continues
;   Tile offset   : 0
;   Split data    : No
;
; This file was generated by GBMB v1.8



 SECTION "Fondo", ROM0

mapafondo::
DB $00,$00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00,$00
DB $00
mapafondoend::
; End of MAPAFONDO.Z80
