; TILEFONDO.ASM
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 0
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Tiles", ROM0

; Start of tile array.
tilefondo::
    db $FF, $FF  ; Línea 1: pasa a 16 bits, 
    db $FF, $FF  ; Línea 2  se agrupan menor y mayor
    db $FF, $FF  ; Línea 3  16/2 = 8. cada fila 8 pixeles
    db $FF, $FF  ; Línea 4
    db $FF, $FF  ; Línea 5
    db $FF, $FF  ; Línea 6
    db $FF, $FF  ; Línea 7
    db $FF, $FF  ; Línea 8 
tilefondoend::

SpaceShip::
    db $18, $00  ; Línea 1: 00011000
    db $3C, $00  ; Línea 2: 00111100
    db $7E, $00  ; Línea 3: 01111110
    db $FF, $00  ; Línea 4: 11111111
    db $BD, $00  ; Línea 5: 10111101
    db $99, $00  ; Línea 6: 10011001
    db $81, $00  ; Línea 7: 10000001
    db $00, $00  ; Línea 8: 00000000
SpaceShipEnd::

Ball:
    dw `00033000
    dw `00322300
    dw `03222230
    dw `03222230
    dw `00322300
    dw `00033000
    dw `00000000
    dw `00000000
BallEnd:

;UN TILE SON 16 BYTES EN MEMORIA

; End of TILEFONDO.Z80
